package requests

type Item struct {
	ExchangedInvoiceDocumentIdentifier                               string   `json:"ExchangedInvoiceDocumentIdentifier"`
	InvoiceDocumentItemIdentifier                                    string   `json:"InvoiceDocumentItemIdentifier"`
	InvoiceDocumentItemCategoryCode                                  *string  `json:"InvoiceDocumentItemCategoryCode"`
	ReferencedSalesOrderDocumentIssuerAssignedIdentifier             *string  `json:"ReferencedSalesOrderDocumentIssuerAssignedIdentifier"`
	ReferencedSalesOrderDocumentRevisionIdentifier                   *string  `json:"ReferencedSalesOrderDocumentRevisionIdentifier"`
	ReferencedOrdersDocumentIssuerAssignedIdentifier                 *string  `json:"ReferencedOrdersDocumentIssuerAssignedIdentifier"`
	ReferencedOrdersDocumentRevisionIdentifier                       *string  `json:"ReferencedOrdersDocumentRevisionIdentifier"`
	ReferencedContractDocumentIssuedAssignedIdentifier               *string  `json:"ReferencedContractDocumentIssuedAssignedIdentifier"`
	ReferencedContractDocumentRevisionIdentifier                     *string  `json:"ReferencedContractDocumentRevisionIdentifier"`
	TradeShipToPartyIdentifier                                       *string  `json:"TradeShipToPartyIdentifier"`
	TradeShipToPartyGlobalIdentifier                                 *string  `json:"TradeShipToPartyGlobalIdentifier"`
	TradeShipToPartyName                                             *string  `json:"TradeShipToPartyName"`
	ShipToPartyAddressPostalCode                                     *string  `json:"ShipToPartyAddressPostalCode"`
	ShipToPartyAddressLineOne                                        *string  `json:"ShipToPartyAddressLineOne"`
	ShipToPartyAddressLineTwo                                        *string  `json:"ShipToPartyAddressLineTwo"`
	ShipToPartyAddressLineThree                                      *string  `json:"ShipToPartyAddressLineThree"`
	TradeShipToPartyAddressCountryIdentifier                         *string  `json:"TradeShipToPartyAddressCountryIdentifier"`
	SupplyChainEventDeliveryOccurrenceDate                           *string  `json:"SupplyChainEventDeliveryOccurrenceDate"`
	ReferencedDeliverySlipDocumentIssuerAssignedIdentifier           *string  `json:"ReferencedDeliverySlipDocumentIssuerAssignedIdentifier"`
	ReferencedDeliverySlipDocumentRevisionIdentifier                 *string  `json:"ReferencedDeliverySlipDocumentRevisionIdentifier"`
	ReferencedDeliverySlipDocumentTypeCode                           *string  `json:"ReferencedDeliverySlipDocumentTypeCode"`
	ReferencedDeliverySlipDocumentCategoryCode                       *string  `json:"ReferencedDeliverySlipDocumentCategoryCode"`
	ReferencedDeliverySlipDocumentSubtypeCode                        *string  `json:"ReferencedDeliverySlipDocumentSubtypeCode"`
	SubordinateTradelineItemCategory                                 *string  `json:"SubordinateTradelineItemCategory"`
	ReferencedSalesOrderDocumentItemLineIssuerAssignedIdentifier     *string  `json:"ReferencedSalesOrderDocumentItemLineIssuerAssignedIdentifier"`
	ReferencedSalesOrderDocumentItemLineIssuerAssignedItemIdentifier *string  `json:"ReferencedSalesOrderDocumentItemLineIssuerAssignedItemIdentifier"`
	ReferencedSalesOrderDocumentItemLineRevisionIdentifier           *string  `json:"ReferencedSalesOrderDocumentItemLineRevisionIdentifier"`
	ReferencedDocumentIssuerAssignedIdentification                   *string  `json:"ReferencedDocumentIssuerAssignedIdentification"`
	ReferencedDocumentItemLineIssuerAssignedIdentification           *string  `json:"ReferencedDocumentItemLineIssuerAssignedIdentification"`
	ReferencedDocumentRevisionIdentifier                             *string  `json:"ReferencedDocumentRevisionIdentifier"`
	ItemLineReferencedOrdersDocumentIssuerAssignedIdentifier         *string  `json:"ItemLineReferencedOrdersDocumentIssuerAssignedIdentifier"`
	ItemLineReferencedOrdersDocumentItemLineIssuerAssignedIdentifier *string  `json:"ItemLineReferencedOrdersDocumentItemLineIssuerAssignedIdentifier"`
	ItemLineReferencedOrdersDocumentRevisionIdentifier               *string  `json:"ItemLineReferencedOrdersDocumentRevisionIdentifier"`
	ItemLineReferencedDocumentTypeCode                               *string  `json:"ItemLineReferencedDocumentTypeCode"`
	IsAttachmentBinaryObjectReferencedByItemLine                     *bool    `json:"IsAttachmentBinaryObjectReferencedByItemLine"`
	ItemLineReferencedDocumentCategoryCode                           *string  `json:"ItemLineReferencedDocumentCategoryCode"`
	ItemLineReferencedDocumentSubtypeCode                            *string  `json:"ItemLineReferencedDocumentSubtypeCode"`
	TradePriceTypeCode                                               *string  `json:"TradePriceTypeCode"`
	TradePriceChargeAmount                                           *float32 `json:"TradePriceChargeAmount"`
	TradePriceBasisQuantity                                          *float32 `json:"TradePriceBasisQuantity"`
	TradePriceBasisQuantityUnitCode                                  *string  `json:"TradePriceBasisQuantityUnitCode"`
	SupplyChainTradeDeliveryItemLineProductPackageQuantity           *float32 `json:"SupplyChainTradeDeliveryItemLineProductPackageQuantity"`
	SupplyChainTradeItemLineProductDeliveryUnitQuantity              *float32 `json:"SupplyChainTradeItemLineProductDeliveryUnitQuantity"`
	SupplyChainTradeDeliveryItemLineProductPerPackageUnitQuantity    *float32 `json:"SupplyChainTradeDeliveryItemLineProductPerPackageUnitQuantity"`
	SupplyChainTradeDeliveryItemLineProductBilledQuantity            *float32 `json:"SupplyChainTradeDeliveryItemLineProductBilledQuantity"`
	SupplyChainTradeDeliveryItemLineProductQuantityUnitCode          *string  `json:"SupplyChainTradeDeliveryItemLineProductQuantityUnitCode"`
	SupplyChainTradeItemLineSettlementDirectionCode                  *string  `json:"SupplyChainTradeItemLineSettlementDirectionCode"`
	ItemLineTradeTaxTypeCode                                         *string  `json:"ItemLineTradeTaxTypeCode"`
	ItemLineTradeTaxBasisAmount                                      *float32 `json:"ItemLineTradeTaxBasisAmount"`
	ItemLineTradeTaxCategoryCode                                     *string  `json:"ItemLineTradeTaxCategoryCode"`
	ItemLineTradeTaxCategoryName                                     *string  `json:"ItemLineTradeTaxCategoryName"`
	ItemLineTradeTaxRateApplicablePercent                            *float32 `json:"ItemLineTradeTaxRateApplicablePercent"`
	ItemLineTradeTaxGrandTotalAmount                                 *float32 `json:"ItemLineTradeTaxGrandTotalAmount"`
	ItemLineTradeTaxLocalTaxSystemIdentifier                         *string  `json:"ItemLineTradeTaxLocalTaxSystemIdentifier"`
	ItemLineTradeIsRefundOrAddAllowanceChargeIndicator               *bool    `json:"ItemLineTradeIsRefundOrAddAllowanceChargeIndicator"`
	ItemLineTradeAllowanceRefundOrAddChargeActualAmount              *float32 `json:"ItemLineTradeAllowanceRefundOrAddChargeActualAmount"`
	ItemLineTradeAllowanceRefundOrAddChargeReasonCode                *string  `json:"ItemLineTradeAllowanceRefundOrAddChargeReasonCode"`
	ItenLineRefundOrAddAllowanceChargeReasonText                     *string  `json:"ItenLineRefundOrAddAllowanceChargeReasonText"`
	ItemLineSpecifiedPeriodStartDate                                 *string  `json:"ItemLineSpecifiedPeriodStartDate"`
	ItemLineSpecifiedPeriodEndDate                                   *string  `json:"ItemLineSpecifiedPeriodEndDate"`
	TradeProductIdentifier                                           *string  `json:"TradeProductIdentifier"`
	TradeProductName                                                 *string  `json:"TradeProductName"`
	TradeProductDescription                                          *string  `json:"TradeProductDescription"`
	TradeProductTypeCode                                             *string  `json:"TradeProductTypeCode"`
}
