package dpfm_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	Document      struct {
		DocumentNo     string `json:"document_no"`
		DeliverTo      string `json:"deliver_to"`
		Quantity       string `json:"quantity"`
		PickedQuantity string `json:"picked_quantity"`
		Price          string `json:"price"`
		Batch          string `json:"batch"`
	} `json:"document"`
	BusinessPartner struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"business_partner"`
	APISchema     string   `json:"api_schema"`
	Accepter      []string `json:"accepter"`
	MaterialCode  string   `json:"material_code"`
	Plant         string   `json:"plant/supplier"`
	Stock         string   `json:"stock"`
	DocumentType  string   `json:"document_type"`
	DocumentNo    string   `json:"document_no"`
	PlannedDate   string   `json:"planned_date"`
	ValidatedDate string   `json:"validated_date"`
	Deleted       bool     `json:"deleted"`
}

type SDC struct {
	ConnectionKey            string                   `json:"connection_key"`
	Result                   bool                     `json:"result"`
	RedisKey                 string                   `json:"redis_key"`
	Filepath                 string                   `json:"filepath"`
	APIStatusCode            int                      `json:"api_status_code"`
	RuntimeSessionID         string                   `json:"runtime_session_id"`
	BusinessPartnerID        *int                     `json:"business_partner"`
	ServiceLabel             string                   `json:"service_label"`
	InvoicesEDIForSMEsHeader InvoicesEDIForSMEsHeader `json:"InvoicesEDIForSMEs"`
	APISchema                string                   `json:"api_schema"`
	Accepter                 []string                 `json:"accepter"`
	Deleted                  bool                     `json:"deleted"`
}

type InvoicesEDIForSMEsHeader struct {
	ExchangedInvoiceDocumentIdentifier                                           string                   `json:"ExchangedInvoiceDocumentIdentifier"`
	InvoiceDocument                                                              *string                  `json:"InvoiceDocument"`
	ExchangedDocumentContextSpecifiedTransactionIdentifier                       *string                  `json:"ExchangedDocumentContextSpecifiedTransactionIdentifier"`
	ExchangedDocumentContextProcessingTransactionDateTime                        *string                  `json:"ExchangedDocumentContextProcessingTransactionDateTime"`
	DocumentContextParameterIdentifier                                           *string                  `json:"DocumentContextParameterIdentifier"`
	DocumentContextParameterValueText                                            *string                  `json:"DocumentContextParameterValueText"`
	DocumentVersionIdentifierOfTransactionProcess                                *string                  `json:"DocumentVersionIdentifier"`
	DocumentVersionIssueDateOfTransactionProcess                                 *string                  `json:"DocumentVersionIssueDate"`
	DocumentContextParameterScenarioIdentifier                                   *string                  `json:"DocumentContextParameterScenarioIdentifier"`
	DocumentContextParameterScenarioValueText                                    *string                  `json:"DocumentContextParameterScenarioValueText"`
	DocumentContextParameterApplicationIdentifier                                *string                  `json:"DocumentContextParameterApplicationIdentifier"`
	DocumentContextParameterApplicationValueText                                 *string                  `json:"DocumentContextParameterApplicationValueText"`
	DocumentContextParameterBusinessFieldIdentifier                              *string                  `json:"DocumentContextParameterBusinessFieldIdentifier"`
	DocumentContextParameterBusinessFieldValueText                               *string                  `json:"DocumentContextParameterBusinessFieldValueText"`
	DocumentVersionIdentifierOfBusinessFunction                                  *string                  `json:"DocumentVersionIdentificationIdentifier"`
	DocumentVersionIssueDateOfBusinessFunction                                   *string                  `json:"DocumentVersionIssueDateOfBusinessFunction"`
	ExchangedInvoiceDocumentName                                                 *string                  `json:"ExchangedInvoiceDocumentName"`
	ExchangedInvoiceDocumentTypeCode                                             *string                  `json:"ExchangedInvoiceDocumentTypeCode"`
	ExchangedInvoiceDocumentIssueDate                                            *string                  `json:"ExchangedInvoiceDocumentIssueDate"`
	ExchangedInvoiceDocumentPreviousRevisionIdentifier                           *string                  `json:"ExchangedInvoiceDocumentPreviousRevisionIdentifier"`
	ExchangedInvoiceDocumentCategoryCode                                         *string                  `json:"ExchangedInvoiceDocumentCategoryCode"`
	ExchangedInvoiceDocumentSubtypeCode                                          *string                  `json:"ExchangedInvoiceDocumentSubtypeCode"`
	NoteInvoiceDocumentSubjectText                                               *string                  `json:"NoteInvoiceDocumentSubjectText"`
	NoteInvoiceDocumentContentText                                               *string                  `json:"NoteInvoiceDocumentContentText"`
	ReferencedDocumentIssuerAssignedIdentifier                                   *string                  `json:"ReferencedDocumentIssuerAssignedIdentifier"`
	NoteInvoiceDocumentIdentifier                                                *string                  `json:"NoteInvoiceDocumentIdentifier"`
	ReferencedDocumentIssueDate                                                  *string                  `json:"ReferencedDocumentIssueDate"`
	ReferencedDocumentRevisionIdentifier                                         *string                  `json:"ReferencedDocumentRevisionIdentifier"`
	ReferencedDocumentInformationText                                            *string                  `json:"ReferencedDocumentInformationText"`
	ReferencedDocumentTypeCode                                                   *string                  `json:"ReferencedDocumentTypeCode"`
	IsAttachmentBinaryObject                                                     *bool                    `json:"IsAttachmentBinaryObject"`
	ReferencedDocumentSubtypeCode                                                *string                  `json:"ReferencedDocumentSubtypeCode"`
	SpecifiedBinaryFileIdentifier                                                *string                  `json:"SpecifiedBinaryFileIdentifier"`
	SpecifiedBinaryFileNameText                                                  *string                  `json:"SpecifiedBinaryFileNameText"`
	SpecifiedBinaryFileURIIdentifier                                             *string                  `json:"SpecifiedBinaryFileURIIdentifier"`
	SpecifiedBinaryFileMIMECode                                                  *string                  `json:"SpecifiedBinaryFileMIMECode"`
	SpecifiedBinaryFileDescriptionText                                           *string                  `json:"SpecifiedBinaryFileDescriptionText"`
	TradeSellerIdentifier                                                        *string                  `json:"TradeSellerIdentifier"`
	TradeSellerGlobalIdentifier                                                  *string                  `json:"TradeSellerGlobalIdentifier"`
	TradeSellerName                                                              *string                  `json:"TradeSellerName"`
	TradeContactSellerIdentifier                                                 *string                  `json:"TradeContactSellerIdentifier"`
	TradeContactSellerPersonName                                                 *string                  `json:"TradeContactSellerPersonName"`
	TradeContactSellerDepartmentName                                             *string                  `json:"TradeContactSellerDepartmentName"`
	TradeContactSellerPersonIdentifier                                           *string                  `json:"TradeContactSellerPersonIdentifier"`
	SellerTelephoneNumber                                                        *string                  `json:"SellerTelephoneNumber"`
	SellerFaxNumber                                                              *string                  `json:"SellerFaxNumber"`
	SellerEmailAddress                                                           *string                  `json:"SellerEmailAddress"`
	SellerAddressPostalCode                                                      *string                  `json:"SellerAddressPostalCode"`
	SellerAddressLineOne                                                         *string                  `json:"SellerAddressLineOne"`
	SellerAddressLineTwo                                                         *string                  `json:"SellerAddressLineTwo"`
	SellerAddressLineThree                                                       *string                  `json:"SellerAddressLineThree"`
	SellerAddressCountryIdentifier                                               *string                  `json:"SellerAddressCountryIdentifier"`
	TradeBuyerIdentifier                                                         *string                  `json:"TradeBuyerIdentifier"`
	TradeBuyerGlobalIdentifier                                                   *string                  `json:"TradeBuyerGlobalIdentifier"`
	TradeBuyerName                                                               *string                  `json:"TradeBuyerName"`
	TradeBillToPartyRegisteredIdentifier                                         *string                  `json:"TradeBillToPartyRegisteredIdentifier"`
	TradeContactBuyerIdentifier                                                  *string                  `json:"TradeContactBuyerIdentifier"`
	TradeContactBuyerPersonName                                                  *string                  `json:"TradeContactBuyerPersonName"`
	TradeContactBuyerDepartmentName                                              *string                  `json:"TradeContactBuyerDepartmentName"`
	TradeContactBuyerPersonIdentifier                                            *string                  `json:"TradeContactBuyerPersonIdentifier"`
	BuyerTelephoneNumber                                                         *string                  `json:"BuyerTelephoneNumber"`
	BuyerFaxNumber                                                               *string                  `json:"BuyerFaxNumber"`
	BuyerEmailAddress                                                            *string                  `json:"BuyerEmailAddress"`
	BuyerAddressPostalCode                                                       *string                  `json:"BuyerAddressPostalCode"`
	BuyerAddressLineOne                                                          *string                  `json:"BuyerAddressLineOne"`
	BuyerAddressLineTwo                                                          *string                  `json:"BuyerAddressLineTwo"`
	BuyerAddressLineThree                                                        *string                  `json:"BuyerAddressLineThree"`
	BuyerAddressCountryIdentifier                                                *string                  `json:"BuyerAddressCountryIdentifier"`
	ProjectIdentifier                                                            *string                  `json:"ProjectIdentifier"`
	ProjectName                                                                  *string                  `json:"ProjectName"`
	SupplyChainTradeSettlementTaxCurrencyCode                                    *string                  `json:"SupplyChainTradeSettlementTaxCurrencyCode"`
	SupplyChainTradeSettlementInvoiceDocumentCurrencyCode                        *string                  `json:"SupplyChainTradeSettlementInvoiceDocumentCurrencyCode"`
	SupplyChainTradeSettlementPaymentCurrencyCode                                *string                  `json:"SupplyChainTradeSettlementPaymentCurrencyCode"`
	TradeBillFromPartyIdentifier                                                 *string                  `json:"TradeBillFromPartyIdentifier"`
	TradeBillFromPartyGlobalIdentifier                                           *string                  `json:"TradeBillFromPartyGlobalIdentifier"`
	TradeBillFromPartyName                                                       *string                  `json:"TradeBillFromPartyName"`
	TradeBillFromPartyRegisteredIdentifier                                       *string                  `json:"TradeBillFromPartyRegisteredIdentifier"`
	TradeContactBillFromPartyIdentifier                                          *string                  `json:"TradeContactBillFromPartyIdentifier"`
	TradeContactBillFromPartyPersonNameText                                      *string                  `json:"TradeContactBillFromPartyPersonNameText"`
	TradeContactBillFromPartyDepartmentNameText                                  *string                  `json:"TradeContactBillFromPartyDepartmentNameText"`
	TradeContactBillFromPartyPersonIdentifier                                    *string                  `json:"TradeContactBillFromPartyPersonIdentifier"`
	BillFromPartyTelephoneNumber                                                 *string                  `json:"BillFromPartyTelephoneNumber"`
	BillFromPartyFaxNumber                                                       *string                  `json:"BillFromPartyFaxNumber"`
	BillFromPartyEMailAddress                                                    *string                  `json:"BillFromPartyEMailAddress"`
	BillFromPartyAddressPostalCode                                               *string                  `json:"BillFromPartyAddressPostalCode"`
	BillFromPartyAddressLineOne                                                  *string                  `json:"BillFromPartyAddressLineOne"`
	BillFromPartyAddressLineTwo                                                  *string                  `json:"BillFromPartyAddressLineTwo"`
	BillFromPartyAddressLineThree                                                *string                  `json:"BillFromPartyAddressLineThree"`
	BillFromPartyAddressCountryIdentifier                                        *string                  `json:"BillFromPartyAddressCountryIdentifier"`
	TradeSettlementPaymentMeansTypeCode                                          *string                  `json:"TradeSettlementPaymentMeansTypeCode"`
	TradeSettlementPaymentMeansInformationText                                   *string                  `json:"TradeSettlementPaymentMeansInformationText"`
	TradeSettlementPaymentMeansPaidAmount                                        *float32                 `json:"TradeSettlementPaymentMeansPaidAmount"`
	CreditorFinancialAccountName                                                 *string                  `json:"CreditorFinancialAccountName"`
	CreditorFinancialAccountProprietaryIdentifier                                *string                  `json:"CreditorFinancialAccountProprietaryIdentifier"`
	CreditorFinancialAccountTypeCode                                             *string                  `json:"CreditorFinancialAccountTypeCode"`
	CreditorFinancialInstitutionName                                             *string                  `json:"CreditorFinancialInstitutionName"`
	CreditorFinancialInstitutionJapanFinancialInstitutionCommonIdentifier        *string                  `json:"CreditorFinancialInstitutionJapanFinancialInstitutionCommonIdentifier"`
	BranchFinancialInstitutionIdentifier                                         *string                  `json:"BranchFinancialInstitutionIdentifier"`
	BranchFinancialInstitutionName                                               *string                  `json:"BranchFinancialInstitutionName"`
	TradeSettlementFinancialCardIdentifier                                       *string                  `json:"TradeSettlementFinancialCardIdentifier"`
	TradeSettlementFinancialCardTypeCode                                         *string                  `json:"TradeSettlementFinancialCardTypeCode"`
	TradeSettlementFinancialCardholderName                                       *string                  `json:"TradeSettlementFinancialCardholderName"`
	TradeSettlementFinancialCardIssuingCompanyName                               *string                  `json:"TradeSettlementFinancialCardIssuingCompanyName"`
	TradeRefundOrAddAllowanceChargeChargeIndicator                               *string                  `json:"TradeRefundOrAddAllowanceChargeChargeIndicator"`
	TradeRefundOrAddTaxCalculatedAmount                                          *float32                 `json:"TradeRefundOrAddTaxCalculatedAmount"`
	TradeRefundOrAddTaxCalculatedRate                                            *float32                 `json:"TradeRefundOrAddTaxCalculatedRate"`
	TradeRefundOrAddTaxBasisAmount                                               *float32                 `json:"TradeRefundOrAddTaxBasisAmount"`
	TradeRefundOrAddTaxCategoryCode                                              *string                  `json:"TradeRefundOrAddTaxCategoryCode"`
	TradeTaxCalculatedAmount                                                     *float32                 `json:"TradeTaxCalculatedAmount"`
	TradeTaxTypeCode                                                             *string                  `json:"TradeTaxTypeCode"`
	TradeTaxBasisAmount                                                          *float32                 `json:"TradeTaxBasisAmount"`
	TradeTaxCategoryCode                                                         *string                  `json:"TradeTaxCategoryCode"`
	TradeTaxCurrencyCode                                                         *string                  `json:"TradeTaxCurrencyCode"`
	TradeTaxCategoryNameText                                                     *string                  `json:"TradeTaxCategoryNameText"`
	TradeTaxRateApplicablePercent                                                *float32                 `json:"TradeTaxRateApplicablePercent"`
	TradeTaxGrandTotalAmount                                                     *float32                 `json:"TradeTaxGrandTotalAmount"`
	TradeTaxCalculationMethodCode                                                *string                  `json:"TradeTaxCalculationMethodCode"`
	TradeTaxLocalTaxSystemIdentifier                                             *string                  `json:"TradeTaxLocalTaxSystemIdentifier"`
	InvoiceDocumentSpecifiedPeriodStartDate                                      *string                  `json:"InvoiceDocumentSpecifiedPeriodStartDate"`
	InvoiceDocumentSpecifiedPeriodEndDate                                        *string                  `json:"InvoiceDocumentSpecifiedPeriodEndDate"`
	TradePaymentTermsDescriptionText                                             *string                  `json:"TradePaymentTermsDescriptionText"`
	TradePaymentTermsDueDate                                                     *string                  `json:"TradePaymentTermsDueDate"`
	TradePaymentTermsTypeCode                                                    *string                  `json:"TradePaymentTermsTypeCode"`
	TradeInvoiceDocumentSettlementMonetarySummationChargeTotalAmount             *float32                 `json:"TradeInvoiceDocumentSettlementMonetarySummationChargeTotalAmount"`
	TradeInvoiceDocumentSettlementMonetarySummationAllowanceTotalAmount          *float32                 `json:"TradeInvoiceDocumentSettlementMonetarySummationAllowanceTotalAmount"`
	TradeInvoiceDocumentSettlementMonetarySummationTaxBasisTotalAmount           *float32                 `json:"TradeInvoiceDocumentSettlementMonetarySummationTaxBasisTotalAmount"`
	TradeInvoiceDocumentSettlementMonetarySummationTaxTotalAmount                *float32                 `json:"TradeInvoiceDocumentSettlementMonetarySummationTaxTotalAmount"`
	TradeInvoiceDocumentSettlementMonetarySummationGrandTotalAmount              *float32                 `json:"TradeInvoiceDocumentSettlementMonetarySummationGrandTotalAmount"`
	TradeInvoiceDocumentSettlementMonetarySummationTotalPrepaidAmount            *float32                 `json:"TradeInvoiceDocumentSettlementMonetarySummationTotalPrepaidAmount"`
	TradeInvoiceDocumentSettlementMonetarySummationDuePayableAmount              *float32                 `json:"TradeInvoiceDocumentSettlementMonetarySummationDuePayableAmount"`
	TradeInvoiceDocumentSettlementMonetarySummationNetLineTotalAmount            *float32                 `json:"TradeInvoiceDocumentSettlementMonetarySummationNetLineTotalAmount"`
	TradeInvoiceDocumentSettlementMonetarySummationIncludingTaxesLineTotalAmount *float32                 `json:"TradeInvoiceDocumentSettlementMonetarySummationIncludingTaxesLineTotalAmount"`
	FinancialAdjustmentReasonCode                                                *string                  `json:"FinancialAdjustmentReasonCode"`
	FinancialAdjustmentReasonText                                                *string                  `json:"FinancialAdjustmentReasonText"`
	FinancialAdjustmentActualAmount                                              *float32                 `json:"FinancialAdjustmentActualAmount"`
	FinancialAdjustmentDirectionCode                                             *string                  `json:"FinancialAdjustmentDirectionCode"`
	FixedDocumentReferencedDocumentIssuerAssignedIdentifier                      *string                  `json:"FixedDocumentReferencedDocumentIssuerAssignedIdentifier"`
	FixedDocumentReferencedDocumentIssueDate                                     *string                  `json:"FixedDocumentReferencedDocumentIssueDate"`
	FixedDocumentReferencedDocumentRevisionIdentifier                            *string                  `json:"FixedDocumentReferencedDocumentRevisionIdentifier"`
	FixedDocumentReferencedDocumentTypeCode                                      *string                  `json:"FixedDocumentReferencedDocumentTypeCode"`
	FixedDocumentReferencedDocumentSubtypeCode                                   *string                  `json:"FixedDocumentReferencedDocumentSubtypeCode"`
	TradelAdjustmentTaxCalculatedAmount                                          *float32                 `json:"TradelAdjustmentTaxCalculatedAmount"`
	TradelAdjustmentTaxCalculatedRate                                            *float32                 `json:"TradelAdjustmentTaxCalculatedRate"`
	TradelAdjustmentTaxCategoryCode                                              *string                  `json:"TradelAdjustmentTaxCategoryCode"`
	TradeSettlementMonetarySummationAddChargeTotalAmount                         *float32                 `json:"TradeSettlementMonetarySummationAddChargeTotalAmount"`
	TradeSettlementMonetarySummationRefundAllowanceTotalAmount                   *float32                 `json:"TradeSettlementMonetarySummationRefundAllowanceTotalAmount"`
	TradeSettlementMonetarySummationPreDocumentGrandTotalAmount                  *float32                 `json:"TradeSettlementMonetarySummationPreDocumentGrandTotalAmount"`
	TradeSettlementMonetarySummationPreDocumentTotalPrePaidAmount                *float32                 `json:"TradeSettlementMonetarySummationPreDocumentTotalPrePaidAmount"`
	TradeSettlementMonetarySummationDuePayableAmount                             *float32                 `json:"TradeSettlementMonetarySummationDuePayableAmount"`
	DuePayableAmountReferencedDocumentIdentification                             *string                  `json:"DuePayableAmountReferencedDocumentIdentification"`
	DuePayableAmountReferencedDocumentIssueDate                                  *string                  `json:"DuePayableAmountReferencedDocumentIssueDate"`
	DuePayableAmountReferencedDocumentRevisionIdentifier                         *string                  `json:"DuePayableAmountReferencedDocumentRevisionIdentifier"`
	DuePayableAmountReferencedDocumentInformationText                            *string                  `json:"DuePayableAmountReferencedDocumentInformationText"`
	IsAttachmentBinaryObjectReferencedByDuePayableAmount                         *float32                 `json:"IsAttachmentBinaryObjectReferencedByDuePayableAmount"`
	DuePayableAmountReferencedDocumentTypeCode                                   *string                  `json:"DuePayableAmountReferencedDocumentTypeCode"`
	DuePayableAmountReferencedDocumentSubtypeCode                                *string                  `json:"DuePayableAmountReferencedDocumentSubtypeCode"`
	InvoicesEDIForSMEsItem                                                       []InvoicesEDIForSMEsItem `json:"InvoicesEDIForSMEsItem"`
}

type InvoicesEDIForSMEsItem struct {
	ExchangedInvoiceDocumentIdentifier                               string   `json:"ExchangedInvoiceDocumentIdentifier"`
	InvoiceDocumentItemIdentifier                                    string   `json:"InvoiceDocumentItemIdentifier"`
	InvoiceDocumentItemCategoryCode                                  *string  `json:"InvoiceDocumentItemCategoryCode"`
	ReferencedSalesOrderDocumentIssuerAssignedIdentifier             *string  `json:"ReferencedSalesOrderDocumentIssuerAssignedIdentifier"`
	ReferencedSalesOrderDocumentRevisionIdentifier                   *string  `json:"ReferencedSalesOrderDocumentRevisionIdentifier"`
	ReferencedOrdersDocumentIssuerAssignedIdentifier                 *string  `json:"ReferencedOrdersDocumentIssuerAssignedIdentifier"`
	ReferencedOrdersDocumentRevisionIdentifier                       *string  `json:"ReferencedOrdersDocumentRevisionIdentifier"`
	ReferencedContractDocumentIssuedAssignedIdentifier               *string  `json:"ReferencedContractDocumentIssuedAssignedIdentifier"`
	ReferencedContractDocumentRevisionIdentifier                     *string  `json:"ReferencedContractDocumentRevisionIdentifier"`
	TradeShipToPartyIdentifier                                       *string  `json:"TradeShipToPartyIdentifier"`
	TradeShipToPartyGlobalIdentifier                                 *string  `json:"TradeShipToPartyGlobalIdentifier"`
	TradeShipToPartyName                                             *string  `json:"TradeShipToPartyName"`
	ShipToPartyAddressPostalCode                                     *string  `json:"ShipToPartyAddressPostalCode"`
	ShipToPartyAddressLineOne                                        *string  `json:"ShipToPartyAddressLineOne"`
	ShipToPartyAddressLineTwo                                        *string  `json:"ShipToPartyAddressLineTwo"`
	ShipToPartyAddressLineThree                                      *string  `json:"ShipToPartyAddressLineThree"`
	TradeShipToPartyAddressCountryIdentifier                         *string  `json:"TradeShipToPartyAddressCountryIdentifier"`
	SupplyChainEventDeliveryOccurrenceDate                           *string  `json:"SupplyChainEventDeliveryOccurrenceDate"`
	ReferencedDeliverySlipDocumentIssuerAssignedIdentifier           *string  `json:"ReferencedDeliverySlipDocumentIssuerAssignedIdentifier"`
	ReferencedDeliverySlipDocumentRevisionIdentifier                 *string  `json:"ReferencedDeliverySlipDocumentRevisionIdentifier"`
	ReferencedDeliverySlipDocumentTypeCode                           *string  `json:"ReferencedDeliverySlipDocumentTypeCode"`
	ReferencedDeliverySlipDocumentCategoryCode                       *string  `json:"ReferencedDeliverySlipDocumentCategoryCode"`
	ReferencedDeliverySlipDocumentSubtypeCode                        *string  `json:"ReferencedDeliverySlipDocumentSubtypeCode"`
	SubordinateTradelineItemCategory                                 *string  `json:"SubordinateTradelineItemCategory"`
	ReferencedSalesOrderDocumentItemLineIssuerAssignedIdentifier     *string  `json:"ReferencedSalesOrderDocumentItemLineIssuerAssignedIdentifier"`
	ReferencedSalesOrderDocumentItemLineIssuerAssignedItemIdentifier *string  `json:"ReferencedSalesOrderDocumentItemLineIssuerAssignedItemIdentifier"`
	ReferencedSalesOrderDocumentItemLineRevisionIdentifier           *string  `json:"ReferencedSalesOrderDocumentItemLineRevisionIdentifier"`
	ReferencedDocumentIssuerAssignedIdentification                   *string  `json:"ReferencedDocumentIssuerAssignedIdentification"`
	ReferencedDocumentItemLineIssuerAssignedIdentification           *string  `json:"ReferencedDocumentItemLineIssuerAssignedIdentification"`
	ReferencedDocumentRevisionIdentifier                             *string  `json:"ReferencedDocumentRevisionIdentifier"`
	ItemLineReferencedOrdersDocumentIssuerAssignedIdentifier         *string  `json:"ItemLineReferencedOrdersDocumentIssuerAssignedIdentifier"`
	ItemLineReferencedOrdersDocumentItemLineIssuerAssignedIdentifier *string  `json:"ItemLineReferencedOrdersDocumentItemLineIssuerAssignedIdentifier"`
	ItemLineReferencedOrdersDocumentRevisionIdentifier               *string  `json:"ItemLineReferencedOrdersDocumentRevisionIdentifier"`
	ItemLineReferencedDocumentTypeCode                               *string  `json:"ItemLineReferencedDocumentTypeCode"`
	IsAttachmentBinaryObjectReferencedByItemLine                     *bool    `json:"IsAttachmentBinaryObjectReferencedByItemLine"`
	ItemLineReferencedDocumentCategoryCode                           *string  `json:"ItemLineReferencedDocumentCategoryCode"`
	ItemLineReferencedDocumentSubtypeCode                            *string  `json:"ItemLineReferencedDocumentSubtypeCode"`
	TradePriceTypeCode                                               *string  `json:"TradePriceTypeCode"`
	TradePriceChargeAmount                                           *float32 `json:"TradePriceChargeAmount"`
	TradePriceBasisQuantity                                          *float32 `json:"TradePriceBasisQuantity"`
	TradePriceBasisQuantityUnitCode                                  *string  `json:"TradePriceBasisQuantityUnitCode"`
	SupplyChainTradeDeliveryItemLineProductPackageQuantity           *float32 `json:"SupplyChainTradeDeliveryItemLineProductPackageQuantity"`
	SupplyChainTradeItemLineProductDeliveryUnitQuantity              *float32 `json:"SupplyChainTradeItemLineProductDeliveryUnitQuantity"`
	SupplyChainTradeDeliveryItemLineProductPerPackageUnitQuantity    *float32 `json:"SupplyChainTradeDeliveryItemLineProductPerPackageUnitQuantity"`
	SupplyChainTradeDeliveryItemLineProductBilledQuantity            *float32 `json:"SupplyChainTradeDeliveryItemLineProductBilledQuantity"`
	SupplyChainTradeDeliveryItemLineProductQuantityUnitCode          *string  `json:"SupplyChainTradeDeliveryItemLineProductQuantityUnitCode"`
	SupplyChainTradeItemLineSettlementDirectionCode                  *string  `json:"SupplyChainTradeItemLineSettlementDirectionCode"`
	ItemLineTradeTaxTypeCode                                         *string  `json:"ItemLineTradeTaxTypeCode"`
	ItemLineTradeTaxBasisAmount                                      *float32 `json:"ItemLineTradeTaxBasisAmount"`
	ItemLineTradeTaxCategoryCode                                     *string  `json:"ItemLineTradeTaxCategoryCode"`
	ItemLineTradeTaxCategoryName                                     *string  `json:"ItemLineTradeTaxCategoryName"`
	ItemLineTradeTaxRateApplicablePercent                            *float32 `json:"ItemLineTradeTaxRateApplicablePercent"`
	ItemLineTradeTaxGrandTotalAmount                                 *float32 `json:"ItemLineTradeTaxGrandTotalAmount"`
	ItemLineTradeTaxLocalTaxSystemIdentifier                         *string  `json:"ItemLineTradeTaxLocalTaxSystemIdentifier"`
	ItemLineTradeIsRefundOrAddAllowanceChargeIndicator               *bool    `json:"ItemLineTradeIsRefundOrAddAllowanceChargeIndicator"`
	ItemLineTradeAllowanceRefundOrAddChargeActualAmount              *float32 `json:"ItemLineTradeAllowanceRefundOrAddChargeActualAmount"`
	ItemLineTradeAllowanceRefundOrAddChargeReasonCode                *string  `json:"ItemLineTradeAllowanceRefundOrAddChargeReasonCode"`
	ItenLineRefundOrAddAllowanceChargeReasonText                     *string  `json:"ItenLineRefundOrAddAllowanceChargeReasonText"`
	ItemLineSpecifiedPeriodStartDate                                 *string  `json:"ItemLineSpecifiedPeriodStartDate"`
	ItemLineSpecifiedPeriodEndDate                                   *string  `json:"ItemLineSpecifiedPeriodEndDate"`
	TradeProductIdentifier                                           *string  `json:"TradeProductIdentifier"`
	TradeProductName                                                 *string  `json:"TradeProductName"`
	TradeProductDescription                                          *string  `json:"TradeProductDescription"`
	TradeProductTypeCode                                             *string  `json:"TradeProductTypeCode"`
}
